{"uuid": "a8b18b4e-145c-4df1-966c-7d2948401936", "children": ["0311c499-a080-4f7a-87b3-98776b1c63e7"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=120.0.6099.225)\nStacktrace:\n\tGetHandleVerifier [0x00007FF660482142+3514994]\n\t(No symbol) [0x00007FF6600A0CE2]\n\t(No symbol) [0x00007FF65FF476AA]\n\t(No symbol) [0x00007FF65FF20AFD]\n\t(No symbol) [0x00007FF65FFBCB1B]\n\t(No symbol) [0x00007FF65FFD218F]\n\t(No symbol) [0x00007FF65FFB5D93]\n\t(No symbol) [0x00007FF65FF84BDC]\n\t(No symbol) [0x00007FF65FF85C64]\n\tGetHandleVerifier [0x00007FF6604AE16B+3695259]\n\tGetHandleVerifier [0x00007FF660506737+4057191]\n\tGetHandleVerifier [0x00007FF6604FE4E3+4023827]\n\tGetHandleVerifier [0x00007FF6601D04F9+689705]\n\t(No symbol) [0x00007FF6600AC048]\n\t(No symbol) [0x00007FF6600A8044]\n\t(No symbol) [0x00007FF6600A81C9]\n\t(No symbol) [0x00007FF6600988C4]\n\tBaseThreadInitThunk [0x00007FFCD8FE7344+20]\n\tRtlUserThreadStart [0x00007FFCDA3226B1+33]\n\n", "trace": "  File \"C:\\Users\\Dell\\PycharmProjects\\pythonProject\\pyWebAutomation1x\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\PycharmProjects\\pythonProject\\pyWebAutomation1x\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\PycharmProjects\\pythonProject\\pyWebAutomation1x\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\PycharmProjects\\pythonProject\\pyWebAutomation1x\\tests\\vwoLoginTests\\test_vwologin.py\", line 18, in setup\n    driver.get(\"https://app.vwo.com\")\n  File \"C:\\Users\\Dell\\PycharmProjects\\pythonProject\\pyWebAutomation1x\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 357, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Dell\\PycharmProjects\\pythonProject\\pyWebAutomation1x\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Dell\\PycharmProjects\\pythonProject\\pyWebAutomation1x\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1705623317589, "stop": 1705623626690}], "start": 1705623317589, "stop": 1705623640063}